server:
  port: 8001
spring:
  application:
    name: authService
  datasource:
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
#将登录认证服务注册到Eureka中
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
feign:
  client:
    config:
      default:
        loggerLevel: BASIC # 日志级别